services:
  runner:
    image: ghcr.io/fykosak/github-runner:master
    restart: on-failure:3
    env_file: 'env.env'
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'
